const elements = [
    { name: 'hydrogen', category: 'reactive-nonmetal', row: 1, column: 1 },
    { name: 'helium', category: 'noble-gas', row: 1, column: 18 },
    { name: 'lithium', category: 'alkali-metal', row: 2, column: 1 },
    { name: 'beryllium', category: 'alkaline-earth-metal', row: 2, column: 2 },
    { name: 'boron', category: 'semimetal', row: 2, column: 13 },
    { name: 'carbon', category: 'reactive-nonmetal', row: 2, column: 14 },
    { name: 'nitrogen', category: 'reactive-nonmetal', row: 2, column: 15 },
    { name: 'oxygen', category: 'reactive-nonmetal', row: 2, column: 16 },
    { name: 'fluorine', category: 'halogen', row: 2, column: 17 },
    { name: 'neon', category: 'noble-gas', row: 2, column: 18 },
    { name: 'sodium', category: 'alkali-metal', row: 3, column: 1 },
    { name: 'magnesium', category: 'alkaline-earth-metal', row: 3, column: 2 },
    { name: 'aluminum', category: 'weak-metal', row: 3, column: 13 },
    { name: 'silicon', category: 'semimetal', row: 3, column: 14 },
    { name: 'phosphorus', category: 'reactive-nonmetal', row: 3, column: 15 },
    { name: 'sulfur', category: 'reactive-nonmetal', row: 3, column: 16 },
    { name: 'chlorine', category: 'halogen', row: 3, column: 17 },
    { name: 'argon', category: 'noble-gas', row: 3, column: 18 },
    { name: 'potassium', category: 'alkali-metal', row: 4, column: 1 },
    { name: 'calcium', category: 'alkaline-earth-metal', row: 4, column: 2 },
    { name: 'scandium', category: 'transition-metal', row: 4, column: 3 },
    { name: 'titanium', category: 'transition-metal', row: 4, column: 4 },
    { name: 'vanadium', category: 'transition-metal', row: 4, column: 5 },
    { name: 'chromium', category: 'transition-metal', row: 4, column: 6 },
    { name: 'manganese', category: 'transition-metal', row: 4, column: 7 },
    { name: 'iron', category: 'transition-metal', row: 4, column: 8 },
    { name: 'cobalt', category: 'transition-metal', row: 4, column: 9 },
    { name: 'nickel', category: 'transition-metal', row: 4, column: 10 },
    { name: 'copper', category: 'transition-metal', row: 4, column: 11 },
    { name: 'zinc', category: 'transition-metal', row: 4, column: 12 },
    { name: 'gallium', category: 'weak-metal', row: 4, column: 13 },
    { name: 'germanium', category: 'semimetal', row: 4, column: 14 },
    { name: 'arsenic', category: 'semimetal', row: 4, column: 15 },
    { name: 'selenium', category: 'reactive-nonmetal', row: 4, column: 16 },
    { name: 'bromine', category: 'halogen', row: 4, column: 17 },
    { name: 'krypton', category: 'noble-gas', row: 4, column: 18 },
    { name: 'rubidium', category: 'alkali-metal', row: 5, column: 1 },
    { name: 'strontium', category: 'alkaline-earth-metal', row: 5, column: 2 },
    { name: 'yttrium', category: 'transition-metal', row: 5, column: 3 },
    { name: 'zirconium', category: 'transition-metal', row: 5, column: 4 },
    { name: 'niobium', category: 'transition-metal', row: 5, column: 5 },
    { name: 'molybdenum', category: 'transition-metal', row: 5, column: 6 },
    { name: 'technetium', category: 'transition-metal', row: 5, column: 7 },
    { name: 'ruthenium', category: 'transition-metal', row: 5, column: 8 },
    { name: 'rhodium', category: 'transition-metal', row: 5, column: 9 },
    { name: 'palladium', category: 'transition-metal', row: 5, column: 10 },
    { name: 'silver', category: 'transition-metal', row: 5, column: 11 },
    { name: 'cadmium', category: 'transition-metal', row: 5, column: 12 },
    { name: 'indium', category: 'weak-metal', row: 5, column: 13 },
    { name: 'tin', category: 'weak-metal', row: 5, column: 14 },
    { name: 'antimony', category: 'semimetal', row: 5, column: 15 },
    { name: 'tellurium', category: 'semimetal', row: 5, column: 16 },
    { name: 'iodine', category: 'halogen', row: 5, column: 17 },
    { name: 'xenon', category: 'noble-gas', row: 5, column: 18 },
    { name: 'cesium', category: 'alkali-metal', row: 6, column: 1 },
    { name: 'barium', category: 'alkaline-earth-metal', row: 6, column: 2 },
    { name: 'lanthanum', category: 'lanthanide', row: 9, column: 3 },
    { name: 'cerium', category: 'lanthanide', row: 9, column: 4 },
    { name: 'praseodymium', category: 'lanthanide', row: 9, column: 5 },
    { name: 'neodymium', category: 'lanthanide', row: 9, column: 6 },
    { name: 'promethium', category: 'lanthanide', row: 9, column: 7 },
    { name: 'samarium', category: 'lanthanide', row: 9, column: 8 },
    { name: 'europium', category: 'lanthanide', row: 9, column: 9 },
    { name: 'gadolinium', category: 'lanthanide', row: 9, column: 10 },
    { name: 'terbium', category: 'lanthanide', row: 9, column: 11 },
    { name: 'dysprosium', category: 'lanthanide', row: 9, column: 12 },
    { name: 'holmium', category: 'lanthanide', row: 9, column: 13 },
    { name: 'erbium', category: 'lanthanide', row: 9, column: 14 },
    { name: 'thulium', category: 'lanthanide', row: 9, column: 15 },
    { name: 'ytterbium', category: 'lanthanide', row: 9, column: 16 },
    { name: 'lutetium', category: 'lanthanide', row: 9, column: 17 },
    { name: 'hafnium', category: 'transition-metal', row: 6, column: 4 },
    { name: 'tantalum', category: 'transition-metal', row: 6, column: 5 },
    { name: 'tungsten', category: 'transition-metal', row: 6, column: 6 },
    { name: 'rhenium', category: 'transition-metal', row: 6, column: 7 },
    { name: 'osmium', category: 'transition-metal', row: 6, column: 8 },
    { name: 'iridium', category: 'transition-metal',row: 6, column: 9 },
    { name: 'platinum', category: 'transition-metal', row: 6, column: 10 },
    { name: 'gold', category: 'transition-metal', row: 6, column: 11 },
    { name: 'mercury', category: 'transition-metal', row: 6, column: 12 },
    { name: 'thallium', category: 'weak-metal', row: 6, column: 13 },
    { name: 'lead', category: 'weak-metal', row: 6, column: 14 },
    { name: 'bismuth', category: 'weak-metal', row: 6, column: 15 },
    { name: 'polonium', category: 'semimetal', row: 6, column: 16 },
    { name: 'astatine', category: 'halogen', row: 6, column: 17 },
    { name: 'radon', category: 'noble-gas', row: 6, column: 18 },
    { name: 'francium', category: 'alkali-metal', row: 7, column: 1 },
    { name: 'radium', category: 'alkaline-earth-metal', row: 7, column: 2 },
    { name: 'actinium', category: 'actinide', row: 10, column: 3 },
    { name: 'thorium', category: 'actinide', row: 10, column: 4 },
    { name: 'protactinium', category: 'actinide', row: 10, column: 5 },
    { name: 'uranium', category: 'actinide', row: 10, column: 6 },
    { name: 'neptunium', category: 'actinide', row: 10, column: 7 },
    { name: 'plutonium', category: 'actinide', row: 10, column: 8 },
    { name: 'americium', category: 'actinide', row: 10, column: 9 },
    { name: 'curium', category: 'actinide', row: 10, column: 10 },
    { name: 'berkelium', category: 'actinide', row: 10, column: 11 },
    { name: 'californium', category: 'actinide', row: 10, column: 12 },
    { name: 'einsteinium', category: 'actinide', row: 10, column: 13 },
    { name: 'fermium', category: 'actinide', row: 10, column: 14 },
    { name: 'mendelevium', category: 'actinide', row: 10, column: 15 },
    { name: 'nobelium', category: 'actinide', row: 10, column: 16 },
    { name: 'lawrencium', category: 'actinide', row: 10, column: 17 },
    { name: 'rutherfordium', category: 'unknown', row: 7, column: 4 },
    { name: 'dubnium', category: 'unknown', row: 7, column: 5 },
    { name: 'seaborgium', category: 'unknown', row: 7, column: 6 },
    { name: 'bohrium', category: 'unknown', row: 7, column: 7 },
    { name: 'hassium', category: 'unknown', row: 7, column: 8 },
    { name: 'meitnerium', category: 'unknown', row: 7, column: 9 },
    { name: 'darmstadtium', category: 'unknown', row: 7, column: 10 },
    { name: 'roentgenium', category: 'unknown', row: 7, column: 11 },
    { name: 'copernicium', category: 'unknown', row: 7, column: 12 },
    { name: 'nihonium', category: 'unknown', row: 7, column: 13 },
    { name: 'flerovium', category: 'unknown', row: 7, column: 14 },
    { name: 'moscovium', category: 'unknown', row: 7, column: 15 },
    { name: 'livermorium', category: 'unknown', row: 7, column: 16 },
    { name: 'tennessine', category: 'unknown', row: 7, column: 17 },
    { name: 'oganesson', category: 'unknown', row: 7, column: 18 }
];

const table = document.getElementById('periodic-table');

// Dynamic DOM Node generation 
elements.forEach(el => {
    const card = document.createElement('div');
    card.classList.add('element-card', el.category);
    
    // Explicit placement via CSS Grid line markers
    card.style.gridRowStart = el.row;
    card.style.gridColumnStart = el.column;

    var name = el.name.toLowerCase();
    var link = "materials/" + name + ".html";

    // Interactivity: Event listener configuration
    card.addEventListener('click', () => open(link));
    table.appendChild(card);
});